mysql:  
  image: mysql:latest
  ports:
    - "3306:3306"
  environment:
    MYSQL_DATABASE: database
    MYSQL_USER: root
    MYSQL_PASSWORD: admin123
    MYSQL_ROOT_PASSWORD: admin123

apache:
  build: './apache'
  ports:
    - "80:80"
    - "443:443"
    - "22"
  volumes:
    - ./src:/var/www/html
  links:
    - mysql